name: "Setup"
inputs:
  install:
    description: "Run pnpm install"
    required: false
    default: true
  install-args:
    description: "Args to pass to pnpm install"
    required: false
    default: "--frozen-lockfile"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"
        # This creates an .npmrc that reads the NODE_AUTH_TOKEN environment variable
        # necessary for publish
        registry-url: "https://registry.npmjs.org"

    - name: Install dependencies
      if: ${{ inputs.install }}
      run: pnpm install ${{ inputs.install-args }}
      shell: bash

    - name: Build package
      run: pnpm build
      shell: bash
